### ISSUE TITLE
Minimum price change - timestamp for 24 hour expiration

### ISSUE THREAD

**Issue by whatl3y** [gmx-io/gmx-interface#12]
According to the [minimum price change docs](https://gmxio.gitbook.io/gmx/trading#minimum-price-change), _This requirement only lasts for 24 hours after a position is opened or increased_.

Can we add the expiration time somewhere in the position table or in the modal that pops up if you want to remove your position before this 24 hours is up but you're still under the 1.5% price change?

**Comment by gkrasulya** [comment]
Hi @whatl3y 

There is a warning in the Modal already. The message only shows if price change is less than 1.5 %. In case you don't see it please tell us
![image](https://user-images.githubusercontent.com/748652/136619582-59d4734e-67ec-47fc-a615-90d3346788a1.png)

**Comment by gkrasulya** [comment]
we've implemented this feature
