### ISSUE TITLE
Stablecoin displayed available room does not match contract

### ISSUE THREAD

**Issue by ikmckenz** [gmx-io/gmx-interface#123]
Earlier we had tried to deposit USDC, and the web interface said there was some $1.8m in available room. Deposits were not working and when asking on Discord we were told the following (paraphrased):

> The USDC pool is unfortunately at capacity in the contract there is only ~12k open. It is bit complex but it has to do with how the USDG in the GLP calculates the values of the assets in the pools, will see if the UI can better reflect the available balance.

**Comment by xvi10** [comment]
Sorry for the issue and slow reply, this should be fixed now, but please re-open if not, thank you.
