### ISSUE TITLE
Suggestion: Add QuickNode as RPC Fallback for Arbitrum

### ISSUE THREAD

**Issue by zer0cache** [gmx-io/gmx-interface#201]
QuickNode offers [support for the Arbitrum network](https://www.quicknode.com/chains/arb) and offers a free plan for users. 

I suggest adding QuickNode to the list of [backup RPC providers](https://gmxio.gitbook.io/gmx/trading#backup-rpc-urls) and [events](https://github.com/gmx-io/gmx-interface/blob/14ba5241097ddc41b5c8b500b462bbae48ac7f1d/src/config/events.js#L21) to provide users more options in case there are reliability issues with other providers.

They also provide the [fastest response times in the industry](https://www.quicknode.com/compare), which is a competitive advantage to traders. Every second counts when you're making a trade!

**Comment by Cahl-Dee** [comment]
+1

**Comment by deadlocked247** [comment]
+1

**Comment by netsparkle** [comment]
<3 Quicknode

**Comment by cp0k** [comment]
+1 !

**Comment by xvi10** [comment]
Thank you for the suggestion, have added it to the docs: https://gmxio.gitbook.io/gmx/trading#backup-rpc-urls

Will include it in the events notification if it needs to be announced
