### ISSUE TITLE
Walletconnect?

### ISSUE THREAD

**Issue by sberan** [gmx-io/gmx-interface#30]
I love walletconnect. I think using it would get more users as well. Would you consider a PR implementing walletconnect? If so I will implement the necessary code.

**Comment by gkrasulya** [comment]
Hi @sberan! 

PR would be great. We're still in process of creating some guidelines how to contribute. So be ready that we may ask for some changes during PR review 🙂

Thank you!

**Comment by gkrasulya** [comment]
Hey @sberan. I might have time to work on this next week but I want to avoid double-work. So just wanted to check with you if you're planning or even already implementing this?

**Comment by gkrasulya** [comment]
Working on it here https://github.com/gmx-io/gmx-interface/pull/36

**Comment by sberan** [comment]
Hey I played around with it a bit but didn't get anything working. Looks like you're making great progress!
