### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by pudgefury** [gmx-io/gmx-interface#394]
Hey, I'm a full stack blockchain developer. I wanna contribute this community. Let me know if you are interested, Thanks.

**Comment by sujantkumarkv** [comment]
Hey all, I'm great with python, nodejs and getting up in solidity too. I want to contribute to GMX, let me know the details :)

**Comment by vipineth** [comment]
Please use the appropriate channel and reach out to the team via Telegram regarding this matter. Posting as an issue on Github is not a professional approach. You can find all the relevant information on the subject at https://gmxio.gitbook.io/gmx/community-groups.
