### ISSUE TITLE
kline current low price 

### ISSUE THREAD

**Issue by leo-web3** [gmx-io/gmx-interface#429]
https://github.com/gmx-io/gmx-interface/blob/e136a1172eabd57cbc0411d73cba7eb175059960/src/domain/prices.ts#L292

```typescript
last.low = Math.max(last.low, averagePriceValue);
```
`low`  should be smaller than
use 
`Math.min`

**Comment by DXJ999empireZ** [comment]
query ($marketIds: [String!], $marketIndexAsString: String!) { 
   prices ( 
     where: { 
       id_in: $marketIds 
     } 
     orderBy: timeUpdated 
     orderDirection: desc 
   ) { 
     id 
     price 
     timeUpdated 
   } 
   syntheticMarkets( 
     where: { 
       marketIndex: $marketIndexAsString 
     } 
   ) { <<<**query ($marketIds: [String!], $marketIndexAsString: String!) { 
   prices ( 
     where: { 
       id_in: $marketIds 
     } 
     orderBy: timeUpdated 
     orderDirection: desc 
   ) { 
     id 
     price 
     timeUpdated 
   } 
   syntheticMarkets( 
     where: { 
       marketIndex: $marketIndexAsString 
     } 
   ) { 
                 fundingRateMultiplier_e18 
         } 
 }algorithms:
2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_RND======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.18210 | 0.15281 | 0.07011 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.08623 | 0.04810 | 0.06094 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.00000 | 0.08904 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.6893397068905002 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_PSO======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.22131 | 0.12861 | 0.05966 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.15345 | 0.10486 | 0.28099 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.08028 | 0.02385 | 0.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.053004072893302 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_ACOm======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.37458 | 0.28208 | 0.17991 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.00000 | 1.00000 | 1.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.00000 | 1.00000 | 0.10959 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    5.946151922377553 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_ABC======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.84599 | 0.51308 | 0.22588 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.58850 | 0.21455 | 0.17249 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.47444 | 0.26681 | 0.35941 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    3.661160435265267 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_GWO======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.00000 | 0.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.00000 | 0.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.18977 | 0.04119 | 0.01802 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.24898721240154956 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_COAm======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.00000 | 0.73390 | 0.28892 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.64504 | 0.34034 | 0.21362 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.67153 | 0.34273 | 0.45422 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    4.690306586791184 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_FSS======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.50663 | 0.39737 | 0.11006 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.07806 | 0.05013 | 0.08423 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.01084 | 0.18998 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.4272897567648186 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_FAm======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.64746 | 0.53292 | 0.18102 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.55408 | 0.42299 | 0.64360 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.21167 | 0.28416 | 1.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    4.477897116029613 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_BA======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.43859 | 1.00000 | 1.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.17768 | 0.17477 | 0.33595 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.15329 | 0.07158 | 0.46287 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    3.8147314003892507 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    ================ 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    ================ 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    ================ 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.24898721240154956 | 49cd01def5ccb098045485f3bccc996b87032ec0430015320939-19🔴Gold SELL Now 1840  1842

☑️TP : 1837
☑️TP : 1834
☑️TP : 1820

❌SL : 1850Account could not be found. Please try again and make sure you entered the correct account number with your registered phone number.
 
Err: CBS_ACC_NUM_NOT_FOUND_180 0X63FAAC27https://youtu.be/-Fo25BniG1Ihttps://youtu.be/-Fo25BniG1ICSMS # 55261205 - Modernized ACE Portal Login Outage

https://youtu.be/-Fo25BniG1Ihttps://youtu.be/-Fo25BniG1IAccount could not be found. Please try again and make sure you entered the correct account number with your registered phone number.
 
Err: CBS_ACC_NUM_NOT_FOUND_180 0X63FAAC27🔴Gold SELL Now 1840  1842

☑️TP : 1837
☑️TP : 1834
☑️TP : 1820

❌SL : 1850algorithms:
2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_RND======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.18210 | 0.15281 | 0.07011 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.08623 | 0.04810 | 0.06094 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.00000 | 0.08904 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.6893397068905002 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_PSO======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.22131 | 0.12861 | 0.05966 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.15345 | 0.10486 | 0.28099 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.08028 | 0.02385 | 0.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.053004072893302 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_ACOm======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.37458 | 0.28208 | 0.17991 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.00000 | 1.00000 | 1.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.00000 | 1.00000 | 0.10959 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    5.946151922377553 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_ABC======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.84599 | 0.51308 | 0.22588 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.58850 | 0.21455 | 0.17249 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.47444 | 0.26681 | 0.35941 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    3.661160435265267 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_GWO======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.00000 | 0.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.00000 | 0.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.18977 | 0.04119 | 0.01802 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.24898721240154956 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_COAm======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.00000 | 0.73390 | 0.28892 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.64504 | 0.34034 | 0.21362 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.67153 | 0.34273 | 0.45422 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    4.690306586791184 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_FSS======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.50663 | 0.39737 | 0.11006 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.07806 | 0.05013 | 0.08423 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.00000 | 0.01084 | 0.18998 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    1.4272897567648186 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_FAm======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.64746 | 0.53292 | 0.18102 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.55408 | 0.42299 | 0.64360 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.21167 | 0.28416 | 1.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    4.477897116029613 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    =======C_AO_BA======= 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.43859 | 1.00000 | 1.00000 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.17768 | 0.17477 | 0.33595 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.15329 | 0.07158 | 0.46287 | 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    3.8147314003892507 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    ================ 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    ================ 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    ================ 2023.01.03 17:55:57.386    CalculationTestResults (EURUSD,M1)    0.24898721240154956 | query ($marketIds: [String!], $marketIndexAsString: String!) { 
   prices ( 
     where: { 
       id_in: $marketIds 
     } 
     orderBy: timeUpdated 
     orderDirection: desc 
   ) { 
     id 
     price 
     timeUpdated 
   } 
   syntheticMarkets( 
     where: { 
       marketIndex: $marketIndexAsString 
     } 
   ) { 
                 fundingRateMultiplier_e18 
         } 
 }28875AF1430015320939-1949cd01def5ccb098045485f3bccc996b87032ec0**>>>>
                 fundingRateMultiplier_e18 
         } 
 }

**Comment by vipineth** [comment]
@leo-web3  Thanks for reporting the issue. The issue will be fixed when we merge the PR #433
