### ISSUE TITLE
Position size is showing me the wrong info in testnet

### ISSUE THREAD

**Issue by Sandeep-Narahari** [gmx-io/gmx-interface#633]
![image](https://github.com/gmx-io/gmx-interface/assets/46187761/0f488486-2fb8-4af5-8c5b-f19ba8262def)

for leverage 10 it has to be 16*10 right but its showing the wrong info

**Comment by Sandeep-Narahari** [comment]
Note : I am runing in local

**Comment by xhiroz** [comment]
The screenshot seems correct, check applicable fees to the Pay token under _"Fees and Price Impact"_.

**Comment by Sandeep-Narahari** [comment]
Could you give me the formula how to calculate size delta usd 

i am calculating it as = leverage * eth price in usd (paying amount )* 10**12 

I think we need to substract price imapact fees , don't know how to calculate it 

could you please help me out 
Thank you
