### ISSUE TITLE
WalletConnect issues with Zerion

### ISSUE THREAD

**Issue by ian-eulith** [gmx-io/gmx-interface#679]
Hi there,

We've run into a few issues while trying to connect to app.gmx.io with Zerion mobile wallet on Android via WalletConnect:

- Connection is established but attempting a transaction (a swap) doesn't do anything (just stalls on "Creating order"), nothing in the browser console, nothing pops up on Zerion.
    - There were a bunch of `main.00ff990a.js:2 WebSocket is already in CLOSING or CLOSED state.` errors in the console, from before I attempted my transaction.
- Sometimes scanning the WalletConnect QR code just causes Zerion to spin forever without completing the connection – unclear whether this is a GMX issue or a Zerion one.
    - Could be related to [this issue](https://github.com/WalletConnect/walletconnect-utils/issues/145), which we found with a different dapp.
- Sometimes transactions fail with `No matching key. keychain: <hex string>` without ever making it to the wallet.
    - Some discussion [here](https://github.com/WalletConnect/walletconnect-docs/blob/main/docs/advanced/migration-from-v1.x/dapps/dapp-checklist.md?plain=1#L49) and [here](https://github.com/orgs/WalletConnect/discussions/3291)

**Comment by vipineth** [comment]
We have added support for Zerion wallet now. The issue should be fixed now

https://github.com/gmx-io/gmx-interface/commit/b00252d3ad35dba507778cae9360ab1622fc528d
